FROM nvidia/cuda:10.2-cudnn7-devel-ubuntu18.04

LABEL maintainer "Mark - Auto generated"

ENV DEBIAN_FRONTEND=noninteractive

# Install standard tools
RUN apt-get update && apt-get install -y --no-install-recommends \
    apt-utils software-properties-common dirmngr build-essential \ 
    gpg-agent lsb-release git curl unzip wget gedit nano cmake \
    pkg-config checkinstall yasm libopenblas-dev 

# install python3
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 python3-pip python3-dev python3-tk python3-setuptools

# Update pip
RUN pip3 --no-cache-dir install --upgrade \
    pip setuptools

# Install pytorch
RUN pip3 install torch torchvision

# Install Deep Graph Library (DGL)
RUN pip3 install --pre dgl-cu102
ENV DGLBACKEND=pytorch

# Install pytorch-lightning
RUN pip3 install pytorch-lightning

# Install misc 
RUN pip3 install sklearn gensim pyyaml

RUN rm -rf /var/lib/apt/lists/*

COPY user.sh /usr/local/bin/
CMD bash -C '/usr/local/bin/user.sh'


#six == 1.15.0
#scipy == 1.5.2
#numpy == 1.19.2
#torch == 1.6.0
#gensim == 3.8.3
#dgl == 0.5.2
#networkx == 2.5
#matplotlib == 3.3.2
#sklearn == 0.0
#scikit-learn == 0.23.2
#torch == 1.6.0
#torchvision == 0.7.0
#ezdxf == 0.14.1
#open3d == 0.10.0.0
#pytorch-lightning == 0.9.0